apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-depl
  namespace: shadi-solution
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
        - name: portal
          image: shadi-solution/portal
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: portal-srv
  namespace: shadi-solution
spec:
  selector:
    app: portal
  ports:
    - name: portal
      protocol: TCP
      port: 3000
      targetPort: 80
